AWSTemplateFormatVersion: '2010-09-09'
Description: Brandpoint AI Platform - Secrets Layer (Secrets Manager)

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

  ProjectName:
    Type: String
    Default: brandpoint-ai

Resources:
  #############################################################################
  # External API Keys
  #############################################################################
  OpenAIAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-openai-api-key
      Description: OpenAI API key for ChatGPT queries
      SecretString: '{"apiKey": "PLACEHOLDER_REPLACE_AFTER_DEPLOY"}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: External API integration

  PerplexityAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-perplexity-api-key
      Description: Perplexity API key for AI search queries
      SecretString: '{"apiKey": "PLACEHOLDER_REPLACE_AFTER_DEPLOY"}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: External API integration

  GeminiAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-gemini-api-key
      Description: Google Gemini API key for AI queries
      SecretString: '{"apiKey": "PLACEHOLDER_REPLACE_AFTER_DEPLOY"}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: External API integration

  #############################################################################
  # Hub Integration Secrets
  #############################################################################
  HubServiceAccountSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-hub-service-account-key
      Description: Brandpoint Hub service account API key
      SecretString: '{"apiKey": "PLACEHOLDER_REPLACE_AFTER_DEPLOY", "baseUrl": "https://hub.brandpoint.com/api"}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Hub integration

  HubDatabaseReadOnlySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-ara3-database-readonly
      Description: Read-only connection to ARA3 SQL Server RDS (requires VPC peering to existing Brandpoint VPC)
      SecretString: !Sub |
        {
          "host": "PLACEHOLDER_RDS_ENDPOINT.rds.amazonaws.com",
          "port": "1433",
          "database": "ARA3",
          "username": "PLACEHOLDER_READONLY_USER",
          "password": "PLACEHOLDER_PASSWORD",
          "driver": "ODBC Driver 17 for SQL Server"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: ARA3 database read access for ML training and content queries

  #############################################################################
  # Resource Policy for Lambda Access
  #############################################################################
  SecretsResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref OpenAIAPIKeySecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${Environment}-lambda-role
            Action:
              - secretsmanager:GetSecretValue
            Resource: '*'

Outputs:
  OpenAISecretArn:
    Description: OpenAI API Key Secret ARN
    Value: !Ref OpenAIAPIKeySecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-OpenAISecretArn

  PerplexitySecretArn:
    Description: Perplexity API Key Secret ARN
    Value: !Ref PerplexityAPIKeySecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-PerplexitySecretArn

  GeminiSecretArn:
    Description: Gemini API Key Secret ARN
    Value: !Ref GeminiAPIKeySecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-GeminiSecretArn

  HubServiceAccountSecretArn:
    Description: Hub Service Account Secret ARN
    Value: !Ref HubServiceAccountSecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-HubServiceAccountSecretArn

  HubDatabaseSecretArn:
    Description: Hub Database Read-Only Secret ARN
    Value: !Ref HubDatabaseReadOnlySecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-HubDatabaseSecretArn
